title: Profesor Labarca
timezone: UTC
email: jbkunst@gmail.com
baseurl: ''
url: http://profesorlabarca.cl
markdown: kramdown
include:
- _pages

gems:
- jekyll-paginate

paginate: 4
paginate_path: noticias/page:num/

prose:
  rooturl: '_posts'
  media: 'media'
  metadata:
    _posts:
      - name: "title"
        field:
          element: "text"
          label: "Titulo"
      - name: "date"
        field:
          label: "Fecha"
          element: "text"
          value: "CURRENT_DATETIME"
      - name: "comments"
        field:
          element: "checkbox"
          label: "Comentarios"
          value: true
      - name: "tags"
        field:
          element: "select"
          label: "Categoria"
          options:
            - name: "Informaciones"
              value: "informaciones"
            - name: "Actividades"
              value: "actividades"
            - name: "CMAT"
              value: "cmat"
