---
title: Profesor Labarca
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: jbkunst@gmail.com
baseurl: ''
url: http://profesorlabarca.cl
markdown: kramdown
include:
- _pages
gems:
- jekyll-paginate
paginate: 4
paginate_path: noticias/page:num/
