title: Profesor Labarca
timezone: UTC
email: jbkunst@gmail.com
baseurl: ''
url: http://profesorlabarca.cl
markdown: kramdown
include:
- _pages
gems:
- jekyll-paginate
paginate: 4
paginate_path: noticias/page:num/

prose:
  rooturl: '_posts'
  media: 'media'
  metadata:
    - name: "date"
    field:
      element: "text"
      label: "Date"
      value: "CURRENT_DATETIME"
