title: Profesor Labarca
timezone: UTC
email: jbkunst@gmail.com
baseurl: ''
url: http://profesorlabarca.cl
markdown: kramdown
include:
- _pages

defaults:
  -
    scope:
      path: "posts"
    values:
      layout: "project"

gems:
- jekyll-paginate

paginate: 6
paginate_path: noticias/page:num/

prose:
  siteurl: ""
  rooturl: '_posts'
  media: 'media'
  metadata:
    _posts:
      - name: "title"
        field:
          element: "text"
          label: "Titulo"
      - name: "date"
        field:
          label: "Fecha"
          element: "text"
          value: "CURRENT_DATETIME"
      - name: "featured_image"
        field:
          label: "Imagen"
          element: "text"
      - name: "comments"
        field:
          element: "checkbox"
          label: "Comentarios"
          value: true
      - name: "categories"
        field:
          element: "select"
          label: "Categoria"
          options:
            - name: "Noticias"
              value: "noticias"
            - name: "Actividades"
              value: "actividades"
            - name: "CMAT"
              value: "cmat"
