title: Profesor Labarca
email: jbkunst
baseurl: ""
url: "http://example.com" # the base hostname & protocol for your site
timezone: UTC

# Build settings
markdown: kramdown

include: ['_pages']
permalink: "/:categories/:title/"

# https://jekyllrb.com/docs/pagination/
# https://github.com/jekyll/jekyll/issues/4124#issuecomment-232065435
# https://stackoverflow.com/questions/26048623/jekyll-blog-posts-on-non-index-html-pages
gems:
- jekyll-paginate

paginate: 4
paginate_path: "noticias/page:num/"
